### ISSUE TITLE
background update forward user-agent header

### ISSUE THREAD

**Issue by infokimbrandt** [pintsized/ledge#105]
We're trying to use Ledge, and cache depending on which device the request was made from.

We build the cache_key_spec with "ngx.var.device", but when the background process tries to revalidate the cache it uses the header "lua-resty-http/0.06 (Lua) ngx_lua/9016".

Would it be possible to forward the User-Agent header, and reuse it for the background revalidation?

**Comment by dwightgunning** [comment]
Can you share a gist with how you're attempting to this?

It sounds like the cache key template might not be being applied correctly.

**Comment by hanssonr** [comment]
The problem I think Kim is referring to is that in the revalidation process that uses the lua-resty-http gets the header "lua-resty-http/0.06 (Lua) ngx_lua/9016" since no custom headers are passed through in ledge/jobs/revalidation.lua. The cache key is built upon headers from the initial request that get stripped when the revalidation process is initiated. 

I've made the changes in this pull request ( https://github.com/pintsized/ledge/pull/106 ) that might get the problem clearer.

**Comment by hamishforbes** [comment]
As of v1.17 you should be able to solve this problem by setting:

```lua
ledge:config_set("revalidate_parent_headers", { "user-agent" })
```

**Comment by hanssonr** [comment]
There's still some, in my opinion, strange behaviour when setting headers.

i.e:
```lua
ledge:config_set("revalidate_parent_headers", { "user-agent" })
```
This will tell the config that we would want to override the user-agent header in the ngx.req.get_headers().

ngx.req.get_headers() seems to always return the header lowercased.

In revalidate.lua, line 25-36:
```lua
    local headers = {
        ["Host"]          = job.data.headers["host"], -- Always set host from parent
        ["Cache-Control"] = "max-stale=0, stale-if-error=0",
        ["User-Agent"]    = httpc._USER_AGENT .. " ledge_revalidate/" .. _M._VERSION
    }

    -- Add additional headers from parent
    if job.data.parent_headers then
        for _,hdr in ipairs(job.data.parent_headers) do
            headers[hdr] = job.data.headers[hdr]
        end
    end
```

These "local header" are Camel-spinal-cased which will make our overwrite not function as excepted. We would then have be add "User-Agent" in the config_set above. This way we will be able to override the local User-Agent header, and the "user-agent" from the request can be passed on correctly. In my opinion this feels like a strange behaviour. 

One solution might be to remove the extra User-Agent header set in local headers since i find no use of it. The resty http library will set a default user-agent header if none are passed.

**Comment by pintsized** [comment]
Ah, nice catch. ec6e607 should fix it by ensuring those local headers are treated case-insensitively.
