### ISSUE TITLE
Configureable qless 

### ISSUE THREAD

**Issue by hanssonr** [pintsized/ledge#114]
Hi,

In our project we have a lot of job keys being generated by qless jobs and would like the have em "removed" in a faster pace than what the default values does. What I can see is that qless:new is ran in the function put_background_job and if I put the q:config_set jobs-history-count/jobs-history config keys in there I get the preferred behaviour.

Is there a way right now that i'm missing to configure qless used by ledge or is their any plans in the future to add functionality as such?

Best regards, Rickard

**Comment by pintsized** [comment]
Hmm, yeah. Currently we handle this by instantiating a connection to qless manually outside of Ledge, as part of wider configuration / bootsrap code.

But I guess since Ledge manages all other aspects of using qless (like starting workers), it feels like it could handle config too. There is a plan to add separate host/port config for qless as well, so that you can optionally run it on a different Redis instance (which might be important when it comes to supporting Redis Cluster eventually).

So I guess we should add a new config option, `redis_qless_config`, and have it do a `qless:config_set` for anything in there.

**Comment by hanssonr** [comment]
Thanks for the quick response!

Then I have a follow up question, could there be any known problems by putting the config setting in the put_background_job function to avoid our growing problem as of now?

**Comment by pintsized** [comment]
Yeah I guess that's fine, nothing is going to blow up, though it will obviously run those commands each time a job is scheduled.

It's cleaner to have a snippet of Qless code external to this, which you run once to set your config. Or even just run a Redis query manually when you set the server up?

e.g.

`hmset ql:config jobs-history-count 5000 jobs-history 50000`
