### ISSUE TITLE
Configurable server address/port for background revalidation - Cleanup of failed jobs

### ISSUE THREAD

**Issue by hanssonr** [pintsized/ledge#115]
Hi again,

We've been successfully implementing your feedback from the https://github.com/pintsized/ledge/issues/114 issue and managed to lower the qless jobs history. Though we've noticed that the overall job keys aren't shrinking. This due to the fact that our jobs are failing. So I have numerous questions that might have crossed your minds:

1) Is there by any chance in your future plans to allow the user to change the server address/port on the background-revalidation job? We've noticed that our jobs fails due to this since we're using docker on a Amazon EC2 instance. The IP we're getting from the ngx.var.server_addr is the private IP from the instance and since we're using a load balancer it will fail its request causing a timeout. This will in its turn make the job fail and the keys are building up. (Background: we're using Wordpress and can therefore not use the server address since it will only try to register a new site then)

2) Don't really know if this should go into the qless repo instead, but might as well ask here. Is there a way to clean up failed keys? Right now we're experiencing about 500k keys being generated per day due to the problem above.

3) After we tried to change the server address to in our case, the server name (DNS) we still found that some keys failed due to timeout. There is a configuration option to set the upstream_connect_timeout, this doesn't seem to affect the timeout set by the revalidation job. Is there a chance this is something you might consider to add as well?

Best regards, Rickard

**Comment by pintsized** [comment]
Hey,

1) Well, it wasn't planned for, but I can see that being useful. Generally I'm a bit unhappy with the config options around background revalidation (we have both a callback and a config option). We've been discussing perhaps deprecating both, and having one event fire prior to scheduling a background revalidation, which is passed all relevant parameters allowing you to manipulate basically everything? Should be neater and give better control. I'm working on background revalidation at the moment - adding an option to revalidate on purge, so I'm keen to tidy all of this up.

2) The easiest way is to install [qless-web](https://github.com/hamishforbes/lua-resty-qless-web). You can delete all failed jobs from there (and generally get better visibility of Qless). If things get really hairy, flush the Qless DB - worst case is you lose some GC jobs and have a few uncollected cache entities left around, which will eventually expire.

3) Firstly, this should follow the upstream timeout setting by default (but doesn't currently). Since timeout options need to be passed to the job anyway, the callback mentioned in 1) would give you a hook to override these as needed. So sounds like that's a good idea (rather than loads more config options).

Thoughts?

**Comment by hanssonr** [comment]
Hey, missed your reply!

1) The pre-event seems like a much smoother way to go for the users that want full control. But I've got the feeling that you guys wanted it to feel easy and implemented the config options as well _"Thank for this, and sorry for the delay. We've implemented it in a similar way, with the addition of a config option for simple cases. See #109"_. But I'm more than happy to be able to config it all the way :)

2) I understand the use of qless-web but I was out for more of a programmatic way to say: hey I wanna delete all failed jobs every, say, half hour. I do though understand that it seems crazy to wanna delete failed jobs since I'm missing out on information why some jobs fail. Why I asked were since we did flush the DB once when there was about 12 million failed keys and that made the site unresponsive for about 2 minutes. We probably should have wrote a script emptying in batches but we took a shoot at redis ;) But would there have been a config to emptying once in a while there shouldn't have been a problem.

3) Yea I'm all in for the pre-event configuration, seems like a neat way to go!

Best regards, Rickard

**Comment by pintsized** [comment]
Hey,

1) Yeah, when it first came up my feeling was a simple option would do in most cases, but turns out that was naive. Just seems like in the real world you need quite a lot of control over background revalidation to make it work, so I think it's best to drop that config option in favour of a well documented event.

2) Well yeah, you need to make sure jobs aren't failing really :) But for now, you could run something like this on a cron...

`redis-cli -n 1 eval "repeat local res = redis.call('rpop', 'ql:f:failed-' .. KEYS[1]); redis.call('del', res) until not res" 1 ledge`

...which will delete every job found in the failed-ledge list, and remove them from the list at the same time.

**Comment by pintsized** [comment]
This has now moved to the [before_save_revalidation_data](https://github.com/pintsized/ledge#before_save_revalidation_data) event.
