### ISSUE TITLE
Implementation and configuration questions

### ISSUE THREAD

**Issue by asvinours** [pintsized/ledge#146]
Hello,

I am doing a POC and testing Ledge versus Varnish, hoping to see good results to be able to benefit from the shared backend cache between multiple instances.

I have a few questions:
 - seems it used to be an option called `revalidate_parent_headers`, but this is now gone. Does it mean that by default all the headers from the parent request will be re-used? I need to be sure that the re-validation request is using the same parameters than the original request like user-agent, country-code, etc.

 - We can tweak the cache key by setting certain options. It would be easier if we could have an event for the cache key generation that would receive the request as parameter. Would that be something that could be possible?
I checked the cache_key function (https://github.com/pintsized/ledge/blob/817f22c3401c16ea9275bac42c9cf653774d108a/lib/ledge/handler.lua#L195) and it doesn't seem to have access to the request object.
The easiest option to update the cache key based on the request would then be something like that?
```
location / {
    content_by_lua '
        local country_code = get_request_country_code()
        local device_type = get_device_type()
        ledge:config_set("cache_key_spec", {
            country_code,
            device_type,
            ngx.var.scheme,
            ngx.var.host,
            ngx.var.uri,
            ngx.var.args,
        })
        ledge:run()
    ';
}
```

Thank you

**Comment by pintsized** [comment]
Hi,

Unfortunately (or fortunately, depending on your point of view) you've caught us in the middle of a large refactor, which means that right now the docs and the code base don't correlate properly. The good news is that this refactor has been well worth it, and we're nearly done (hope to have a tagged v2 alpha next week, with better docs). But yes, the bad news is your sample code above isn't going to work with the new version.

You could checkout the v1 branch and work with that - the docs are accurate there. But things are about to change radically, so it might be worth taking another look in a couple of weeks?

If you feel like making it work on the master branch however, I'll try and help, so read on...

On the first point, yes previously there was a slightly confusing scenario where we had both a config option and an event hook for setting revalidation data. Revalidation data is used in a couple of different ways, so it's a little complicated, but the gist is that:

* By default we store the following headers for use in background revalidation: `Host`, `Authorization` and `Cookie`.
* Before they are stored, the event `before_save_revalidation_data` is emitted which passes you `reval_params` and `reval_headers` tables, which you can modify however you like.

The way to think about this is; when a response is saved, which things do I need to remember in order to make a subsequent headless background request succeed?

`reval_params` contains connection data (upstream host / port / timeouts etc).

On the second point, the new version has a bit more flexibility with the cache key spec option, owing in part to how the config system has completely changed. Instead of passing variables which are evaluated there and then, you instead pass string identifiers to place common elements into the cache key (i.e. uri components), or a function returning a run time variable you wish to insert.

Overriding the cache key for your example would look something like this:

```lua
location / {
    content_by_lua_block {
        require("ledge").create_handler({
            cache_key_spec = {
                get_request_country_code,
                get_device_type,
                "scheme",
                "host",
                "port",
                "uri",
                "args",
            }
        }):run()
    }
};
```

That is, your functions are passed in as config values, and are called at run time for each request.

For a bit more info on how to generally configure Ledge right now, with a list of current config options, there's a gist with a few examples here: https://gist.github.com/pintsized/f56c4232a62fd56a4e8fcdc68ebf70de

Hope that helps. Like I said, give us a couple of weeks and things should be much clearer. Apologies for the temporary state of confusion.

**Comment by asvinours** [comment]
Hello,

Thank for all these details, it really helps.
I will wait a few weeks then, see the amazing works you guys did on the new version.

I'll close this issue as you answered my questions.
Thank you again.
